### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ipstas** [skagedal/mmongo#1]
Tried the mmongo and got:

```
/usr/local/lib/node_modules/mmongo/mmongo.js:99
  var ret = child_process.spawnSync('meteor', args);
                          ^
TypeError: Object #<Object> has no method 'spawnSync'
    at getMeteorMongoUrl (/usr/local/lib/node_modules/mmongo/mmongo.js:99:27)
    at main (/usr/local/lib/node_modules/mmongo/mmongo.js:26:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/mmongo/mmongo.js:161:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
    at startup (node.js:121:16)
    at node.js:764:3
```

**Comment by skagedal** [comment]
Hi, thank you for reporting this. I realize now that mmongo needs a Node.js
version of at least 0.12 to run. I should mention in the docs.

Regards, Simon

tisdag 23 juni 2015 skrev ipstas notifications@github.com:

**Comment by bmlyon** [comment]
But Meteor doesn't support 0.12, they're stuck on 0.10.40, so how would that work?

**Comment by skagedal** [comment]
You run mmongo with a regular installation of Node.js, not with the one that comes installed with Meteor. mmongo is really just a wrapper that invokes meteor and mongo; it could just as well have been written as a shell script.

**Comment by skagedal** [comment]
README updated.

**Comment by bmlyon** [comment]
So I guess I will never be able to run mmongo on the same machine as meteor until meteor gets updated to use a newer version of node?

**Comment by skagedal** [comment]
There should be no problem with that. It is, of course, the situation for which I developed `mmongo`, and worked fine for me. Meteor uses its own installation of Node.js and does not care what is otherwise installed on your machine. 

I have, however, only tested `mmongo` with Meteor 1.1 and NodeJS 0.12. If you're having issues with later versions, please do report them.

**Comment by bmlyon** [comment]
From what I understand that may cause trouble with global installs, fibers, certain modules, and other stuff. I guess I'll give it a try and hope that I don't run into issues. Thanks for the help.
